# Copyright 2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.15.0

EAPI=8

inherit cargo git-r3

DESCRIPTION="A modernized, complete, embeddable TeX/LaTeX engine. Tectonic is forked from the XeTeX extension to the classic \"Web2C\" implementation of TeX and uses the TeXLive distribution of support files."
HOMEPAGE="https://tectonic-typesetting.github.io/"

EGIT_REPO_URI="https://github.com/tectonic-typesetting/tectonic"

LICENSE="MIT"
# Dependent crate licenses
LICENSE+=" Apache-2.0 BSD CC0-1.0 ISC MIT Unicode-3.0 ZLIB"
SLOT="0"
KEYWORDS="-*"

src_unpack() {
    git-r3_src_unpack
    cargo_live_src_unpack
}
